### ISSUE TITLE
Can not compile on kali3 kernel 6.5.0

### ISSUE THREAD

**Issue by Ejuc** [EnzephaloN/ncpfs-module#11]
DKMS make.log for ncpfs-2.2.6 for kernel 6.5.0-kali3-amd64 (x86_64)
piektdiena, 2024. gada 19. janvāris, 14:12:22 EET
make -C /lib/modules/6.5.0-kali3-amd64/build M=/var/lib/dkms/ncpfs/2.2.6/build modules
make[1]: Entering directory '/usr/src/linux-headers-6.5.0-kali3-amd64'
  CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/dir.o
  CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/file.o
  CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/inode.o
/var/lib/dkms/ncpfs/2.2.6/build/inode.c: In function ‘ncp_update_dates’:
/var/lib/dkms/ncpfs/2.2.6/build/inode.c:158:9: error: implicit declaration of function ‘inode_set_ctime’; did you mean ‘node_set_state’? [-Werror=implicit-function-declaration]
  158 |         inode_set_ctime(inode, ncp_date_dos2unix(nwi->creationTime, nwi->creationDate), 0);
      |         ^~~~~~~~~~~~~~~
      |         node_set_state
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-6.5.0-kali3-common/scripts/Makefile.build:248: /var/lib/dkms/ncpfs/2.2.6/build/inode.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.5.0-kali3-common/Makefile:2059: /var/lib/dkms/ncpfs/2.2.6/build] Error 2
make[1]: *** [/usr/src/linux-headers-6.5.0-kali3-common/Makefile:246: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.5.0-kali3-amd64'
make: *** [Makefile:48: all] Error 2

**Comment by EnzephaloN** [comment]
Hi there!
You are using the DKMS-version - this repository is about the non-DKMS-version.
Anyway...

You are using the wrong branch (master)! If you've kernel 6.5.x so you have to use branch https://github.com/EnzephaloN/ncpfs_dkms/tree/kernel_6.5 .

**Comment by Ejuc** [comment]
Had problems also on the correct branch. For now I tried to fix this like this but no idea if I did not made it worse:

```
static void ncp_update_dates(struct inode *inode, struct nw_info_struct *nwi)
{
	/* NFS namespace mode overrides others if it's set. */
	ncp_dbg(1, "(%s) nfs.mode=0%o\n", nwi->entryName, nwi->nfs.mode);
	if (nwi->nfs.mode) {
		/* XXX Security? */
		inode->i_mode = nwi->nfs.mode;
	}

	inode->i_blocks = (i_size_read(inode) + NCP_BLOCK_SIZE - 1) >> NCP_BLOCK_SHIFT;

	inode->i_mtime.tv_sec = ncp_date_dos2unix(nwi->modifyTime, nwi->modifyDate);
        struct timespec64 new_time;
        new_time.tv_sec = ncp_date_dos2unix(nwi->creationTime, nwi->creationDate);
        new_time.tv_nsec = 0;  // If no nanosecond data is available
        inode->i_ctime = new_time;
        mark_inode_dirty(inode);
	inode->i_atime.tv_sec = ncp_date_dos2unix(0, nwi->lastAccessDate);
	inode->i_atime.tv_nsec = 0;
	inode->i_mtime.tv_nsec = 0;
        inode->i_ctime = (struct timespec64){0, 0};
        mark_inode_dirty(inode);
}
```
